# docker-compose up -d

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskmanager
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/taskmanager
      PORT: 3001
      NODE_ENV: development
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./frontend
      target: production
      args:
        VITE_API_URL: http://localhost:3001/api
        #VITE_API_URL: http://backend:3001/api/ping
        #VITE_API_URL: http://host.docker.internal:3001/api
    ports:
      #- "80:80"
      #- "3000:3000"
      - "3000:80"
    #environment:
      #VITE_API_URL: http://backend:3001/api
      #VITE_API_URL: http://localhost:3001/api
      #VITE_API_URL: http://host.docker.internal:3001/api

    depends_on:
      - backend

volumes:
  pgdata:
