## Durch Aufteilung in ./frontend und ./backend müssen die build, lint, ... Steps idealerweise seperat ausgeführt werden 

name: CI

on:
  push:
    branches: [main]
  # Warum Aufruf schon von der Pull-Request aus? 
  pull_request:
    branches: [main]

jobs:

  ################
  ### Frontend-Jobs
  ################

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20 #20.x? 
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

  test-frontend:
    runs-on: ubuntu-latest
    needs: lint-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Test frontend
        working-directory: frontend
        run: npm test

  build-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Build frontend
        working-directory: frontend
        run: npm run build

  ################
  ### Backend-Jobs
  ################

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Lint backend
        working-directory: backend
        run: npm run lint

  test-backend:
    runs-on: ubuntu-latest
    needs: lint-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Test backend
        working-directory: backend
        run: npm test

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Build backend
        working-directory: backend
        run: npm run build
